CREATE TABLE Cities
(
CityID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Customers 
(
 CustomerID INT PRIMARY KEY IDENTITY,
 [Name] VARCHAR(50) NOT NULL,
 Birthday DATE,
 CityID INT 

 CONSTRAINT FK_Cities_Customers FOREIGN KEY (CityID) REFERENCES Cities(CityID)
)

CREATE TABLE Orders
(
 OrderID INT PRIMARY KEY IDENTITY,
 CustomerID INT,

 CONSTRAINT FK_Orders_OrderItem FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)

)

CREATE TABLE ItemTypes 
(
ItemTypeID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) NOT NULL,
)

CREATE TABLE Items
(
 ItemID INT PRIMARY KEY IDENTITY,
 [Name] VARCHAR(50) NOT NULL,
 ItemTypeID INT NOT NULL,

 CONSTRAINT FK_Items_ItemTypes FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems
(
 OrderID INT,
 ItemID INT,

 CONSTRAINT PK_OrderID_ItemID PRIMARY KEY(OrderID,ItemID),
 CONSTRAINT FK_Order_Item FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
 CONSTRAINT FK_ITEM_OrderItem FOREIGN KEY (ItemID) REFERENCES Items(ItemID)
)


